// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    ColorBlock: typeof import('./src/components/ColorBlock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ExamsBoard: typeof import('./src/components/ExamsBoard.vue')['default']
    FullView: typeof import('./src/components/ljc/FullView.vue')['default']
    ImgText: typeof import('./src/components/ImgText.vue')['default']
    LectureItem: typeof import('./src/components/LectureItem.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    Navtree: typeof import('./src/components/Navtree.vue')['default']
    NewsBoard: typeof import('./src/components/NewsBoard.vue')['default']
    PassCapsule: typeof import('./src/components/PassCapsule.vue')['default']
    ProgressChart: typeof import('./src/components/ProgressChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VividClick: typeof import('./src/components/ljc/VividClick.vue')['default']
  }
}

export {}
